BEGIN
   BEGIN
   EXECUTE IMMEDIATE 'CREATE TABLE SUPPLIER
   (	
	SUPP_REF 			VARCHAR2(2000) NOT NULL, 
	SUPPLIER_NAME 		VARCHAR2(2000) NOT NULL, 
	SUPP_CONTACT_NAME 	VARCHAR2(2000) NOT NULL, 
	SUPP_ADDRESS 		VARCHAR2(2000) NOT NULL, 
	SUPP_CONTACT_NUMBER VARCHAR2(2000) NOT NULL, 
	SUPP_EMAIL 			VARCHAR2(2000) NULL, 
                                                                        
	CONSTRAINT supplier_pk PRIMARY KEY (SUPP_REF)
	
   )' ;
   EXCEPTION
            WHEN OTHERS THEN IF SQLCODE != 00955 THEN RAISE;
			END IF;
   END;
  
   BEGIN  
   EXECUTE IMMEDIATE 'CREATE TABLE ORDERS 
   (
    ORDER_NO            NUMBER GENERATED ALWAYS AS IDENTITY,   
	ORDER_REF 			VARCHAR2(2000) NOT NULL, 
	ORDER_DATE 			VARCHAR2(2000) NOT NULL,  
	ORDER_TOTAL_AMOUNT 	VARCHAR2(2000)  NULL, 
	ORDER_DESCRIPTION 	VARCHAR2(2000) NOT NULL, 
	ORDER_STATUS 		VARCHAR2(2000) NOT NULL, 
	ORDER_LINE_AMOUNT 	VARCHAR2(2000) NULL,              
	CONSTRAINT order_pk PRIMARY KEY (ORDER_NO, ORDER_REF)
	
   )' ;
   EXCEPTION
            WHEN OTHERS THEN IF SQLCODE != 00955 THEN RAISE;
			END IF;
   END;
   
   BEGIN
    EXECUTE IMMEDIATE 'CREATE TABLE INVOICE
   (	
    INVOICE_NO          NUMBER GENERATED ALWAYS AS IDENTITY,
	ORDER_REF 		    VARCHAR2(2000) NOT NULL, 
	INVOICE_REFERENCE 	VARCHAR2(2000) NULL, 
	INVOICE_DATE 		VARCHAR2(2000) NULL, 
	INVOICE_STATUS 		VARCHAR2(2000) NULL, 
	INVOICE_HOLD_REASON VARCHAR2(2000) NULL, 
	INVOICE_AMOUNT 		VARCHAR2(2000) NULL, 
	INVOICE_DESCRIPTION VARCHAR2(2000) NULL,
	
	CONSTRAINT invoice_pk PRIMARY KEY (INVOICE_NO)	
   )' ;
   EXCEPTION
            WHEN OTHERS THEN IF SQLCODE != 00955 THEN RAISE;
			END IF;
   END;
END;
/